--// insertRegistrosPrueba
-- Migration SQL that makes the change goes here.
INSERT INTO `usuarios` VALUES (1,'admin','aurpi@bitfarm.com.mx','adminadmin','activo','2014-01-16','administrador','','','',NULL,0,0,'',NULL,'null');
INSERT INTO `usuarios` VALUES (2,'rsaldivar','rsaldivar@bitfarm.com.mx','adminadmin','activo','2014-01-16','cliente','','saldivar','Virreyes Oriente',NULL,23,81159123,'roberto.saldivararm@gmail.com',NULL,'null');
INSERT INTO `encuestas` VALUES (1,1,'Encuesta de Clima Laboral','null','2013-12-26','2018-01-09','','rsaldivar@bitfarm.com.mx','hola','bye','activa','activa','publica');
INSERT INTO `preguntas` VALUES (1,'La empresa en general','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',1,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(2,'Economía y condiciones ambientales','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',2,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(3,'¿Considera usted que .','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',3,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(4,'¿Su puesto en la empresa .','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',4,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(5,'Compañeros de trabajo.','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',5,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(6,'Jefe o Superiores.','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',6,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(7,'Reconocimiento.','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',7,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(8,'Remuneración.','1 = No\n2= No, pero con algún matiz\n3 = Si, no / depende\n4 = Si, pero con algún matiz\n5 = Si\nN / A = No aplica',8,1,'matriz','m_radio','matriz radiobuttons','required','activada',NULL,NULL,NULL),(9,'Comentarios Adicionales','Ingresa texto menor a 255 caracteres',9,1,'simple','s_text','input text','required','activada',NULL,NULL,NULL);
INSERT INTO `sub_labels` VALUES (1,'1',1),(2,'2',1),(3,'3',1),(4,'4',1),(5,'5',1),(6,'N/A',1),(7,'N/A',2),(8,'5',2),(9,'4',2),(10,'3',2),(11,'2',2),(12,'1',2),(13,'1',3),(14,'2',3),(15,'3',3),(16,'4',3),(17,'5',3),(18,'N/A',3),(19,'si',4),(20,'no',4),(21,'no se',4),(22,'1',5),(23,'2',5),(24,'3',5),(25,'4',5),(26,'5',5),(27,'N/A',5),(28,'1',6),(29,'2',6),(30,'3',6),(31,'4',6),(32,'5',6),(33,'N/A',6),(34,'1',7),(35,'2',7),(36,'3',7),(37,'4',7),(38,'5',7),(39,'N/A',7),(40,'1',8),(41,'2',8),(42,'3',8),(43,'4',8),(44,'5',8),(45,'N/A',8);
INSERT INTO `sub_preguntas` VALUES (1,'¿Está usted satisfecho con su trayectoria laboral en la empresa?',1),(2,'¿Le gusta la empresa?',1),(3,'¿Se siente orgulloso de pertenecer a ella?',1),(4,'¿Se siente integrado en su empresa?',1),(5,'¿Es usted consciente de lo que aporta a su empresa?',1),(6,'¿Tiene suficiente luz en su lugar de trabajo?',2),(7,'¿Su puesto de trabajo le resulta cómodo?',2),(8,'¿La temperatura es la adecuada en su lugar de trabajo?',2),(9,'¿El nivel de ruido es soportable?',2),(10,'¿Los baños están limpios?',2),(11,'¿Su computadora funciona a una velocidad adecuada?',2),(12,'¿El lugar en el que se sienta le resulta cómodo?',2),(13,'¿Su pantalla está a la altura adecuada para usted?',2),(14,'¿Tiene espacio suficiente en su puesto de trabajo?',2),(15,'... tiene la suficiente capacidad de iniciativa en su trabajo?',3),(16,'... tiene la suficiente autonomía en su trabajo?',3),(17,'...sus ideas son tenidas en cuenta por su jefe o superiores?',3),(18,'...su trabajo es lo suficientemente variado?',3),(19,'... está en relación con la experiencia que usted posee?',4),(20,'... está en relación con su titulación académica?',4),(21,'... está lo suficientemente valorado?',4),(22,'¿Le gustaría permanecer en su puesto de trabajo dentro de su empresa?',4),(23,'¿Existen posibilidades de movilidad en su empresa?',4),(24,'¿Considera que su trabajo está bien remunerado?',8),(25,'¿Su sueldo está en consonancia con los sueldos que hay en su empresa?',8),(26,'¿Cree que su remuneración está por encima de la media en su entorno social, fuera de la empresa?',8),(27,'¿Cree que su sueldo está en consonancia con la situación y marcha económica de la empresa?',8),(28,'¿Considera que realiza un trabajo útil para la empresa?',7),(29,'¿Tiene usted un cierto nivel de seguridad en su trabajo, de cara al futuro?',7),(30,'¿Es posible una promoción laboral basada en resultados?',7),(31,'¿Cree usted que en su empresa existe una igual de oportunidades entre los empleados?',7),(32,'¿Su jefe o superiores le tratan bien, con amabilidad?',6),(33,'¿Considera adecuado el nivel de exigencia por parte de su jefe?',6),(34,'¿Considera que su jefe es comunicativo?',6),(35,'¿Considera usted que su jefe es justo?',6),(36,'¿Existe buena comunicación de arriba a abajo entre jefes y subordinados?',6),(37,'¿Existe buena comunicación de abajo a arriba entre subordinados y jefes?',6),(38,'¿Su jefe o superiores escuchan las opiniones y sugerencias de los empleados?',6),(39,'¿Trabaja usted en equipo con sus compañeros?',5),(40,'¿Si dejase la empresa para ir a otra, lo sentiría por sus compañeros?',5),(41,'¿Considera que tiene un entorno de amigos entre sus compañeros de trabajo?',5),(42,'¿Le ayudaron y apoyaron los primeros días cuando entró en la empresa?',5),(43,'¿Se lleva bien con sus compañeros?',5);

--//@UNDO
-- SQL to undo the change goes here.

DELETE FROM `sub_respuestas` where true;
DELETE FROM `respuestas` where true;
DELETE FROM `sub_preguntas` where true;
DELETE FROM `sub_labels` where true;

DELETE FROM `preguntas` where true;
DELETE FROM `grupos` where true;
DELETE FROM `usuario_tokens` where true;
DELETE FROM `encuestas` where true;
DELETE FROM `usuario_respuestas` where true;
DELETE FROM `usuarios` where true;
